# Generated by Django 5.2 on 2025-04-23 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipecs", "0002_ipecsreport_user_alter_ipecsreport_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipecsreport",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="ipecsreport",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipecsreport",
            name="processed_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipecsreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ipecsreport",
            name="file",
            field=models.FileField(upload_to="ipecs_reports/"),
        ),
        migrations.AlterField(
            model_name="ipecsreport",
            name="file_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ipecsreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ipecsreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
