# Generated by Django 5.2 on 2025-04-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipecs", "0003_remove_ipecsreport_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipecsreport",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ipecsreport",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipecsreport",
            name="processed_records",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ipecsreport",
            name="total_records",
            field=models.IntegerField(default=0),
        ),
    ]
