# Generated by Django 5.2 on 2025-04-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_set_article_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleimage",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
