# Generated by Django 5.2 on 2025-04-21 06:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_articleimage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(
                upload_to="blog/images/", validators=[blog.models.validate_file_size]
            ),
        ),
    ]
